### ISSUE TITLE
Issues in re-running tests

### ISSUE THREAD

**Issue by dannyalan** [matepek/vscode-catch2-test-adapter#114]
After running tests in (both gtest and catch2), tests do not re-run when clicking the run button, either the overall run button of the button for individual tests. 

When looking at the log panel, this message is printed;

[2019-07-26 13:31:26.844] [INFO] [at TestAdapter.run (/home/danny/.vscode-server/extensions/matepek.vscode-catch2-test-adapter-2.6.4/out/src/TestAdapter.js:211:23)] Run is busy

- Extension Version 2.6.4
- VS Code Version 1.36.1
- Windows 10 and Ubuntu 18.04

**Log** Logfile is not generated

**Comment by matepek** [comment]
Please set: `catch2TestExplorer.logfile` and reproduce the bug.
Attach the log file and describe how can be reproduced it step by step. 
Thanks.

**Comment by matepek** [comment]
Anyway, probably one of your tests is in an infinite loop or stuck. Try to set `catch2TestExplorer .defaultRunningTimeoutSec: 10` and see whats happening.

**Comment by dannyalan** [comment]
I'm afraid the log file isn't generated, I will try setting the timeout, that's definitely an idea I didn't think of. I'll let you know how it works out. Thanks

**Comment by matepek** [comment]
👍Let me know about the result. 

That's weird, it should work. Did you set a valid path? (with existing directories) Does your process have write access for that directory?

**Comment by dannyalan** [comment]
Ok, so I have added the logfile entry into the settings, VsCode then throws this error

<img width="929" alt="Screenshot 2019-07-29 at 03 10 36" src="https://user-images.githubusercontent.com/3920354/62017424-7fea5400-b1ae-11e9-8b71-ecf45809e3e5.png">

This is of course in my build directory and therefore the process most definitely has access to write to it.

**Comment by matepek** [comment]
Hello,

I see, thanks for the detailed explanation, this would be helpful, however I don't give support for forks. My extension is [this](https://marketplace.visualstudio.com/items?itemName=matepek.vscode-catch2-test-adapter) and you are using [this](https://marketplace.visualstudio.com/items?itemName=piotrkosek.vscode-gtest-test-adapter-with-code-lens).

It can be easily happen that the bug also exists in case of my extension (especially because linux is part of the issue), but I hope you understand that I don't want to care about forks.

**logfile**: Have you tried using an absolute path?

If you check and prove that the problem still exists I will reopen this issue.

**Comment by dannyalan** [comment]
Ah! I'm sorry, I hadn't realised it was a fork. I'll update the extension to use yours and update the thread appropriately. Thanks
