### ISSUE TITLE
Test adaptor doesn't handle exceptions thrown outside the gtest

### ISSUE THREAD

**Issue by friendnick** [matepek/vscode-catch2-test-adapter#122]
If the code throws the exception outside the google test for example:
```
int globalFunction() {
    throw(std::runtime_error("")); // throwing exception that is outside gtest
}

int globalVar = globalFunction();

TEST() {
    // Google test code here
}
```
Then the test adaptor extension will not list this executable.

The logpanel output for the missing test is the following:
```
[2019-06-26 18:47:42.655] [WARN] [at load.suiteCreationAndLoadingTasks.push.c2fs.isNativeExecutableAsync.then._createSuiteByUri.then (/home/user/.vscode/extensions/matepek.vscode-catch2-test-adapter-2.5.0/out/src/TestExecutableInfo.js:73:38)] Not a test executable: /absoluteTestFolderPath/HistogramTest reason: [Error: FsWrapper.spawnAsync signal: SIGABRT
	at ChildProcess.<anonymous> (/home/user/.vscode/extensions/matepek.vscode-catch2-test-adapter-2.5.0/out/src/FSWrapper.js:36:24)
	at ChildProcess.emit (events.js:182:13)
	at maybeClose (internal/child_process.js:961:16)
	at Socket.ChildProcess.spawn.stream.socket.on (internal/child_process.js:380:11)
	at Socket.emit (events.js:182:13)
	at Pipe.Socket._destroy._handle.close [as _onclose] (net.js:596:12)]
```

**Comment by matepek** [comment]
In this case the extension couldn't identify the executable, so it drops it.
I understand it caused you a bit of a trouble but what should it expect when an executable called with `--help` and ends with `SIGABRT`.

My point of view is that the executable should handle their exception. (`try-catch` in the main and exiting with some code I guess?)

**Comment by friendnick** [comment]
If the test is just not shown in the list, it's super implicit and hard to detect if there is a problem. If the executable matches the test patter, I would like to see it in the list. If not detected as a Google Test, you can mark it with error

**Comment by matepek** [comment]
The reason why I implemented like this because I expected the users to give general patterns more often than specific ones like my default: `**/*test*`. This usually matches on a lot not executables files too.
I might implement a `strict_match` option in the future which would give some error in case of a matched bad file.

**Comment by Malcohol** [comment]
Firstly: Thanks for this project: Very useful.

I just hit this issue, and I thought I'd let you know that it's potentially very confusing. I opened vscode (which had taken an update), made a code change, rebuilt, and my tests disappeared! The absence of all tests strongly suggests a configuration issue (e.g. because of the update), not a code one. Even though I could see that the test executables were failing when I ran them locally, it didn't occur to me that the problems were connected. I lost about an hour to this, because I was looking in the wrong place. I'm unblocked now, and I'll know what to look for next time. Nevertheless, I'd be surprised if others didn't hit this in the future.

**Comment by matepek** [comment]
Hello, thanks ^^
Same issue? Or was my migration failing?

**Comment by Malcohol** [comment]
Basically the same issue. My code change caused an assert to fire during static initialization (C++), and that caused all my test executables to assert on start-up.

**Comment by matepek** [comment]
Thanks for the feedback. I added a `strictPattern` option to the `advancedExecutables`. Available from 3.0.4

**Comment by Malcohol** [comment]
Yes, that might help a little, but may not address the surprise issue, since you have to be aware of the issue to know whether you want to be strict. So I remember an important thing: There was nothing in the output window from TestMate when this issue arose. If you can ensure that matching executables which are rejected for other reasons get a line of console output, that would go a long way to helping.

**Comment by matepek** [comment]
It is mentioned in the log of course. But the logging has to be enabled which is usually not necessary because uses resources.

I see your point but I'm afraid I have no idea what else could we do to avoid this.

**Comment by Malcohol** [comment]
Thanks for giving the issue due consideration :)
