### ISSUE TITLE
List tests even if they fail

### ISSUE THREAD

**Issue by dkuschmierz** [matepek/vscode-catch2-test-adapter#133]
**Is your feature request related to a problem? Please describe.**
If you load the test-explorer view, tests which are failing during test-case scan (e.g. Segfault), are not shown in the list. This behavior prevent the ability to debug this test.

**Describe the solution you'd like**
List also the failing test, but with the red cross...

**Describe alternatives you've considered**

**Additional context**

**Comment by matepek** [comment]
Does your executable results in `segfault` if you start it with --help parameter?

**Comment by dkuschmierz** [comment]
Yes, it does

**Comment by matepek** [comment]
In this case I'm not sure, what would be a good solution, because the extension wouldn't be able to determine the type of the executable: google test, catch2 test or any other executable.

So currently the default executable pattern is like `{out,build}/**/*test*`. Which might found some executables which are not gtest or catch2test. For determining, I'm parsing the output of the invocation with `--help` argument. In case of the executable fails, it can be anything I cannot tell, so the extension will not try.

Debugging it is very easy: try [this](https://code.visualstudio.com/docs/editor/debugging#_launch-configurations)
You can quickly set up a launch for your failing executable.

**Comment by matepek** [comment]
Did my comment help?
