### ISSUE TITLE
Does gdb pretty printer work

### ISSUE THREAD

**Issue by xgdgsc** [matepek/vscode-catch2-test-adapter#146]
From a code search I 'm wondering if gdb pretty printing works for cpptools extension, or do I have to install webfreak.debug to enable pretty printing?

**Comment by matepek** [comment]
Hello,

If you want to register your own pretty-printer functions using this extension's debug functionality and the cpptools, then I might have an answer for you. On other cases please describe the issue because I don't fully understand.

Let me change gdb to lldb, because I am more familiar with that.

The easiest way to to this to create a `~/.lldbinit` file and put my configurations there. This will be loaded at start. I would be surprised if gdb has no such kind of thing.

If you want a project specific configuration you can create a [debugConfigTemplate](https://github.com/matepek/vscode-catch2-test-adapter#catch2testexplorerdebugconfigtemplate) for *cpptools* or any other kind of debug adapters.

In case of *cpptools* you have to set the [setupCommands](https://code.visualstudio.com/docs/cpp/launch-json-reference#_setupcommands).
Something like this:
```
{
            "name": "(lldb) ${label}",
            "type": "cppdbg",
            "request": "launch",
            "program": "${exec}",
            "args": "${argsArray}",
            "stopAtEntry": false,
            "cwd": "${cwd}",
            "environment": [ "${envObj}" ],
            "externalConsole": false,
            "MIMode": "lldb",
            "setupCommands": [ ... ]
},
```

**Comment by xgdgsc** [comment]
Thanks. I know `setupCommands` inside launch.json. I just not sure it will apply when I click debug inside Test Explorer.

**Comment by matepek** [comment]
You have to try then :)

Note: The snippet should be placed into the `settings.json` and not into the `launch.json`.

**Comment by pablomuri** [comment]
Hi! I'm trying to active the pretty printing but I think that this configuration is obsolete, isn't it? I'm using cpptools and gdb in linux. Could you please help me? 

Thanks!

> ```
> "catch2TestExplorer.debugConfigTemplate": {
>             "name": "(lldb) ${label}",
>             "type": "cppdbg",
>             "request": "launch",
>             "program": "${exec}",
>             "args": "${argsArray}",
>             "stopAtEntry": false,
>             "cwd": "${cwd}",
>             "environment": [ "${envObj}" ],
>             "externalConsole": false,
>             "MIMode": "lldb",
>             "setupCommands": [ ... ]
> },
> ```

**Comment by matepek** [comment]
Hello,

‘debugConfigTemplate’ substitutes and forwards everything to the chosen debug adapter. 
How would you achieve this in launch.json just to debug your executable?
(You might have to check the documentation of cpptools)
