### ISSUE TITLE
Allow passing parameters to executable when parsing tests

### ISSUE THREAD

**Issue by jonilaitinen** [matepek/vscode-catch2-test-adapter#165]
I have a gtest executable which needs a path as an argument when executed like this: `/path/to/test-executable /test/files`. Currently it doesn't seem to be possible to give additional run arguments for the test discovery step in similar way as it is for running tests like: `"gtest": {"additionalRunArguments": ["/test/files"]}` 

Would it be possible to enable passing the run arguments in the test discovery step also?

**Comment by matepek** [comment]
I though someone might came up with a need like this thats why I gave a specific name like `additionalRunArguments`. ;)

I could add an `additionalDiscoveryArguments`, yes.

Alternatively you to pass these values through environment variables using the `env` property and get it with [std::getenv](https://en.cppreference.com/w/cpp/utility/program/getenv).
It is cleaner in some ways. Like you don't have to mix gtest arguments with your custom arguments.

If you still think you would prefer the argument passing instead of the environment variable solution let me know.

But please consider that the arguments have an ordering. It might doesn't matter that you perpend or append the arguments:
`./executable myarg --gtest_list_tests` vs `./executable --gtest_list_tests myarg`

**Comment by jonilaitinen** [comment]
Yes I thought about passing the args through environment variables but in my case that would require changing various build scripts and CI build pipelines and it's probably not feasible in this case.

But adding `additionalDiscoveryArguments` would fit my use case perfectly and enable me to use this great extension when developing on my local machine :)

I would imagine the best option would be to pass the additional args first before `--gtest*` arguments since likely the required arguments for the test executable would come first before optional arguments like `--gtest_list_tests`

**Comment by matepek** [comment]
> I would imagine the best option would be to pass the additional args first before --gtest* arguments

Is that a requirement or an opinion?

**Comment by jonilaitinen** [comment]
> > I would imagine the best option would be to pass the additional args first before --gtest* arguments
> 
> Is that a requirement or an opinion?

It is a requirement for my use case, and also an opinion that generally required arguments should come before optional ones :)

**Comment by matepek** [comment]
happy testing with 2.8.12
