### ISSUE TITLE
don't show tests list, not a test executable

### ISSUE THREAD

**Issue by huanghantao** [matepek/vscode-catch2-test-adapter#170]
**Checklist**

- [x] The issue is about this extension and NOT about a fork.
- [x] Check the [known issues](https://github.com/matepek/vscode-catch2-test-adapter#known-issues) list.
- [x] The latest version of the extension was used.

**Describe the bug**

when I click reload tests, it don't show tests list. but I can excute the binary file in shell.

**To Reproduce**

    1. Click on 'reload tests'
    2. See error

```bash
2020-04-03 09:16:43.363] [INFO] pattern /root/codeDir/cppCode/swoole-src/core-tests/bin/core_tests /root/codeDir/phpCode/swoole {
  isAbsolute: true,
  absPattern: '/root/codeDir/cppCode/swoole-src/core-tests/bin/core_tests',
  relativeToWs: '../../cppCode/swoole-src/core-tests/bin/core_tests',
  isPartOfWs: false,
  relativeToWsPosix: '../../cppCode/swoole-src/core-tests/bin/core_tests'
}
[2020-04-03 09:16:43.531] [INFO] Checking file for tests: /root/codeDir/cppCode/swoole-src/core-tests/bin/core_tests
[2020-04-03 09:16:43.706] [DEBUG] Not a test executable: /root/codeDir/cppCode/swoole-src/core-tests/bin/core_tests reason: [Error: Not a supported test executable: /root/codeDir/cppCode/swoole-src/core-tests/bin/core_tests
 output: [object Object]
	at e.TestSuiteInfoFactory._determineTestTypeOfExecutable (/root/.vscode-server/extensions/matepek.vscode-catch2-test-adapter-2.8.12/out/dist/main.js:23:26420)
	at async Promise.all (index 0)
	at async e.TestExecutableInfo.load (/root/.vscode-server/extensions/matepek.vscode-catch2-test-adapter-2.8.12/out/dist/main.js:23:19046)
	at async Promise.all (index 0)]
```
**Desktop**

- Extension Version: 2.8.12
- VS Code Version: 1.43.2
- Catch2 / Google Test / DOCTest Version: 2.8.12
- OS Type and Version: I use vscode in Mac , but I use remote-ssh plugin connect the CentOS Linux release 7.7.1908 (Core) container

**Comment by huanghantao** [comment]
it's my problem, the test file relies on a dynamic library, but it was not found.

**Comment by haytaylan** [comment]
I am having the same issue using my googletest executable on Windows. I'm not having issues when I use Remote-SSH extension on the same project into Linux. I don't have any dynamic libraries at all. I wasn't having this issue with the older version I was using. ( Sadly i can't figure out which version I was on at the time ). However, I haven't changed a configuration on my project since my last test run. I can run the executable on the shell.

Also, the colored output for all extensions is broken somehow after updating to latest version.

**Desktop**

* Extension Version: 2.9.10
* VS Code Version: 1.44.1
* Google Test: 1.10
* OS Type and Version: Windows 7

**Comment by matepek** [comment]
This is a totally new issue, but I will quickly answer here.
So the problem is that your executable produces an output which I cannot parse.
Try to run it with `--help` argument and share the output with me.

Colored output. Yeah, they conflict with each other.. It's a vscode limitation. One thing I can do to implement those features too so you won't see which extension actually does the colorization.
Check next version.

**Comment by haytaylan** [comment]
Colorization seems to work with version 2.9.12, also the extension can now detect my gtest executable. (I tried on another pc). Thank you!
