### ISSUE TITLE
Colored output in Output window prevents link detection for other extensions (e.g. CMake-Tools)

### ISSUE THREAD

**Issue by Torgee** [matepek/vscode-catch2-test-adapter#207]
**Checklist**

- [/] The issue is about this extension and NOT about a fork.
- [/] Check the [known issues](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md#known-issues) list.
- [/] The latest version of the extension was used.

**Describe the bug**

 Colored output in Output window prevents link detection for other extensions (e.g. CMake-Tools)
 After installing TestMate, the output of the CMake-Tools extension is colored, albeit not really 
 correctly. Links to files from said output log are no longer working.

 The 'enableOutputColouring' setting is also not working for me.

 When disabling the TestMate extension (everything else being the same) links are working again.

**To Reproduce**

 1. Install CMake-Tools, C++-Tools and TestMate
 2. Compile something with an error
 3. Try to follow a link to an error (from Output:Cmake/Build) -> does not work

**Desktop**

- Extension Version: 3.2.5
- VS Code Version: 1.45.1
- Catch2 / Google Test / DOCTest Version: n.a.
- OS Type and Version: Win7 64bit
- Using remote-ssh/docker/wsl?: no

**Comment by matepek** [comment]
Hello,
Interestingly the links doesn't work for me on OSX with our without my extension.
I don't see any lines about `registerDocumentLinkProvider` in [vscode-cmake-tools](https://github.com/microsoft/vscode-cmake-tools/search?q=registerDocumentLinkProvider&unscoped_q=registerDocumentLinkProvider).

My conclusion: My extension registers a link provider so vscode itself doesn't try to run the default ones. I'm not sure this is with purpose or not.

**Comment by matepek** [comment]
reported: https://github.com/microsoft/vscode/issues/100106

I've checked my repo. I don't override the link and they say that it should work.

I think It would be good if someone would verify that my repro step works on windows.

**Comment by zrno** [comment]
Can you add an option maybe to disable this feature? Judging by the issue you opened with vs code the problem will not be solved soon and this prevents me and possibly others from using this extension.

**Comment by matepek** [comment]
Would you check this for me?

[vscode-catch2-test-adapter-3.2.7-dev.vsix.zip](https://github.com/matepek/vscode-catch2-test-adapter/files/4820542/vscode-catch2-test-adapter-3.2.7-dev.vsix.zip)

Is it working?

**Comment by zrno** [comment]
Tried it, version was 3.2.7-dev. Links in output tab still not working. After disabling the output the same links immediately start working and are clickable.

**Comment by matepek** [comment]
What do you mean about "disabling the output"?

**Comment by zrno** [comment]
Sorry typo. Should read "After disabling the extension"

**Comment by matepek** [comment]
Would you try this too please?

[vscode-catch2-test-adapter-3.2.6-dev2.vsix.zip](https://github.com/matepek/vscode-catch2-test-adapter/files/4823613/vscode-catch2-test-adapter-3.2.6-dev2.vsix.zip)

**Comment by matepek** [comment]
I consider this issue obsoleted. Let me know if still there are some problem

**Comment by zrno** [comment]
Sorry I forgot to check. The version 3.2.6-dev2 is working correclty

**Comment by zrno** [comment]
3.2.8 is also working correctly

**Comment by matepek** [comment]
I added some workaround. (I felt I have to 😏)

**Comment by zrno** [comment]
Aaand not working again. Or better say it works partially. If there is a compiler error with a link to the exact line, then clicking on the link jumps to the file, but to the top of the file. 

Also the colorization of the output tab is changed completely when using the extension. I would like to keep my old coloring if possible.

**Comment by matepek** [comment]
Please insert the output which is not recognised well. 

About colouring: vscode does not support it well. Cannot disable for specific output tabs.

**Comment by zrno** [comment]
Ill post the exact format of the link that is not recognized when I am back in the office. Until then can I ask that you add a new feature that disables the output coloring of your extension completely? I would like to use all other features of your extension

**Comment by matepek** [comment]
I would but either I disable the whole stuff or leave it as it is.

**Comment by zrno** [comment]
A correct link with the extension disabled:
![image](https://user-images.githubusercontent.com/13214299/87733744-b3414b00-c824-11ea-8d50-b549ded61bb7.png)

The same link with the extension enabled:
![image](https://user-images.githubusercontent.com/13214299/87733537-3a41f380-c824-11ea-8e70-bdb6b274961e.png)
Notice that the line designating the link only goes to .cpp but it doesn't include :8:
So clicking on the link jumps to the top of the file.

Also I would ask again to add a feature flag that disables the coloring of the output. It is unexpected that an extension for unit testing changes the coloring of the output tab.

**Comment by matepek** [comment]
Link will be fixed but I'm afraid vscode api doesn't support disabling the colourings. Either I remove completely or leave it there. Sorry for you inconvenience. 

(There are might one way but have to double check. Don't count on it in the near future though.)

**Comment by dgazzoni** [comment]
To add to this: I'm also affected by this issue.

I'm on macOS, and at first I thought it was an OS-specific issue, since @matepek mentioned that "the links doesn't work for me on OSX with our without my extension". It didn't work for me by merely disabling the C++ TestMate extension either.

However, I found out that there was a second extension breaking the links for me (in my case it was Code Runner, `formulahendry.code-runner`). After disabling Code Runner, then I can reliably reproduce the issue: C++ TestMate version 2.95 works, 2.96 above doesn't (and 3.2.6-dev2, that was linked here, also works when manually installed).

To @matepek: you could try a fresh install of VS Code with the CMake Tools extension alone installed. You should be able to reproduce the issue.

Either way, right now I have to stay on 3.2.6-dev2 because the links from the output window are really useful to me. The coloring is nice and makes the output more readable, and I wish there was a way to leave the coloring there without breaking the links, but I have no idea if that's feasible.

I wonder if in the last few months you didn't discover any alternatives to fix this. I can think of a few solutions but they all seem hacky/high-maintenance: publishing a second extension without the coloring, or publishing a patch that we could use to remove the coloring.

**Comment by dgazzoni** [comment]
BTW: the crazy part is that I swear this was working a few weeks ago, when coloring was already available.

So no idea if this fixed and later broken by a new VS Code version, or another one of my extensions (unlikely because I tried this on a fresh install, VS Code 1.56, with only the CMake Tools and C++ TestMate extension).

**Comment by dgazzoni** [comment]
I just added Google Benchmark to one of my projects, and it looks like 3.2.6-dev2 didn't work with it yet. So I very reluctantly moved to 3.6.26, but I'm really missing the output window links. Would love to see some progress on this.

**Comment by matepek** [comment]
Hello,

The latest version is 3.6.26. I lost track of this and don't even remember what was in `-dev2` prerelease.

However some other big changes are coming in months which will make this issue irrelevant.

Sorry for the inconvenience. 🙏
