### ISSUE TITLE
Option to disable automatic discovery

### ISSUE THREAD

**Issue by axtschmied** [matepek/vscode-catch2-test-adapter#285]
**Checklist**

- [x] Checked [Support page](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md)

**Is your feature request related to a problem? Please describe.**
I build the executable from a shell script and execute it right after building, then I process the code coverage data with gcov. If the TestMate extension runs the executable asynchronously during this process, coverage data can be overwritten, before it is processed.

**Describe the solution you'd like**
A configuration option to disable automatic discovery of test cases, so the executable is only run, if I start it manually.

**Comment by manuelgustavo** [comment]
Agreed, "Disable of automatic discovery" would be very helpful.
This extension is currently being activated on VSCode's startup (since 2021/09/10).
On Windows (as I haven't checked on Linux), that causes problems when a test executable has several build steps (such as embedding manifest), because the file can't be written because it's open exclusively by this extension. 
Note: The `.exe` under which it fails is non-deterministic, but it always fails because in my case I have more than 1000+ unit tests distributed in 30+ test executables. If I keep retrying, it will eventually build completely, but still, it's really annoying. 

And at last but not least, thanks for creating this great extension!

**Comment by matepek** [comment]
Disable automatic discovery or disable automatic reload?

**Comment by manuelgustavo** [comment]
Just an option to not make the extension open the `*test.exe` automatically, as it's still being created (in a multiple steps process).
Maybe that should only happen when one clicks "reload tests".
The problem lies in opening the file exclusively whilst the multiple steps build hasn't just finished yet.

**Comment by matepek** [comment]
Dear User(s),

Version 4+ has been release. Hoping it makes this issue resolved.
If you disagree then please comment `!open`.

**Comment by manuelgustavo** [comment]
Cheers!!!! I will let you know.
