### ISSUE TITLE
A long string literal in test description crashes the test Catch2 test adapter

### ISSUE THREAD

**Issue by jan-revay** [matepek/vscode-catch2-test-adapter#345]
How to reproduce the bug:

```
TEST_CASE("Classic Catch2 SECTION syntax should compile and list in CTest and IDE integrations", "[Dummy]")
{
    CHECK(1 == 1);
} // FAILS

TEST_CASE("Classic Catch2 section syntax should compile and list in CTest and IDE integrations", "[Dummy]")
{
    CHECK(1 == 1);
} // FAILS

TEST_CASE("Classic Catch2 SECTION()", "[Dummy]")
{
    CHECK(1 == 1);
} // PASSES

TEST_CASE("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", "[Dummy]")
{
    CHECK(1 == 1);
} // FAILS
```

**Comment by jan-revay** [comment]
![Screenshot from 2022-04-04 15-29-11](https://user-images.githubusercontent.com/65253638/161554941-e31b0253-dcf4-4ff7-8753-bd666f678948.png)
![Screenshot from 2022-04-04 15-31-54](https://user-images.githubusercontent.com/65253638/161555061-bdb481d9-f9af-4158-af6e-d0a95fe64717.png)

**Comment by matepek** [comment]
See Support page pls.

**Comment by chausner** [comment]
@matepek Setting `CATCH_CONFIG_CONSOLE_WIDTH` to some large value does work but it leads to a bad experience for everyone else who is not using this extension and runs Catch2 on the command-line. Thus, I am bit hesitant to add this define to my code.

Would it be maybe possible to add some heuristics to detect when Catch breaks up the test name and make the parsing more intelligent? Or at least detect when the line break happens in order to give a better error message to the user with a pointer to the support page. When users run into this issue for the first time, I imagine it would often not be clear what the problem is. After all, the error one gets from the extension is not very helpful at the moment.

**Comment by stefanhaller** [comment]
I don't think it's worth adding workarounds for this. The issue is fixed with Catch2 v3, so upgrading to that is the best solution. It's officially released now. (The top-level readme still talks about it being in development, and v2.x being the latest stable version; however, the 3.0.1 release is prominently linked from the homepage, so I suspect the readme just wasn't updated yet.)

**Comment by chausner** [comment]
@stefanhaller Thanks for the notice about this being no longer an issue with Catch2 v3. I agree that updating, if possible, is probably the cleanest solution then. However, v3 requires C++14 or higher, so not every project may be able to update yet. I still think it would be good to include some heuristics to fix this in the extension for now, as long as v2 is still in widespread use.
