### ISSUE TITLE
Support Catch2 special tags

### ISSUE THREAD

**Issue by ferreteleco** [matepek/vscode-catch2-test-adapter#355]
**Checklist**

- [x] Checked [Support page](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md)

**Is your feature request related to a problem? Please describe.**
Catch2 provide some [special tags](https://github.com/catchorg/Catch2/blob/devel/docs/test-cases-and-sections.md#special-tags) aimed at identify "special" tests (tests that may fail, tests that should fail, tests to be ignored when running 'all'...). 

Currently, the test adapter does not provide any info on this. In particular, the !mayfail tag is somehow ignored here since it always get a green check.

**Describe the solution you'd like**
It would be nice to have special identification for those special tags, like, for example:

- a yellow check on tests marked as !mayfail when the assertion does not complete successfully.
- a green / orange / blue check on tests marked as !shouldfail that fail as expected (something to reflect the uncommon nature of the test).

**Describe alternatives you've considered**
For example, executing the tests in the command line identifies those marked with !mayfail tag as:

![image](https://user-images.githubusercontent.com/3154366/180463386-3a826e56-5d3e-473e-8c7c-175268147e32.png)

Thanks in advance!!

**Comment by matepek** [comment]
Hello,

The vscode api currently does not provide possibility for such thing.

I could add some emoji to the label but those would be there even it fails or not.

Don't really like the idea. I mean if someone sets a test 'mayfail' it's their responsibility to be aware of it.
And passing that test is fine since it "may fail". 
Btw one can use filter such as `@testmatecpp:tag."!mayfail"`
