### ISSUE TITLE
Googletest custom failure messages not displayed in the summary

### ISSUE THREAD

**Issue by jakub-dudarewicz** [matepek/vscode-catch2-test-adapter#373]
**Checklist**

- [x] Checked [Support page](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md)

**Is your feature request related to a problem? Please describe.**
Additional googletest assertion failure description passed via `<<` is not displayed in the extension's summary.
![image](https://user-images.githubusercontent.com/88487544/215758351-ca756ffc-736f-478f-ad0d-aeee4079d8a7.png)

**Describe the solution you'd like**
It would be nice to have the custom part of the message be also visible.

**Describe alternatives you've considered**
I can always look at the full terminal output, but the whole purpose of the extension is to not have to look at the whole output.

**Additional context**
This is what the custom message actually looks in the terminal output
![image](https://user-images.githubusercontent.com/88487544/215758634-fad25ab0-8969-4f3f-b0c1-b56c56a9b3ec.png)
Pardon the censorship, the covered parts were sensitive and irrelevant to the issue.

**Comment by matepek** [comment]
It's tricky. Google Test output is not structured so basically I'm parsing a text output.. 
Because... those can be:
- simple print to stdout, not related to previous error
- print to stderr, not related to previous error
- other kind of issue

There is a workaround though. If you would start your message with two spaces(`  `), then [the extension would treat it as part of the previous failure](https://github.com/matepek/vscode-catch2-test-adapter/blob/5edc9e19bfec7d322c0d0f306f2d2cfb75a3ee83/src/framework/GoogleTest/GoogleTestExecutable.ts/#L525).

**Comment by jakub-dudarewicz** [comment]
Thanks, IMO It's a good workaround.
